IDGS903_Tema1/Controllers/Nuevo2Controller.cs
using IDGS903_Tema1.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace IDGS903_Tema1.Controllers
{
    public class Nuevo2Controller : Controller
    {
        // GET: Nuevo2
        public ActionResult Ventana2(OperasBas op)
        {
            op.Operaciones();
            var model = new OperasBas();
            model.Res = op.Res;

            return View(model);
        }

        public ActionResult Calculos(string n1, string n2, string operacion)
        {
            int num1= Convert.ToInt32(n1);
            int num2= Convert.ToInt32(n2);
            //int res= Convert.ToInt32(n1)+Convert.ToInt32(n2);
            float res=0;
            string resultado = "";
            switch (operacion)
            {
                case "1":
                    res= num1 + num2;
                    resultado = res.ToString();
                    break;
                case "2":
                    res = num1 - num2;
                    resultado = res.ToString();
                    break;
                case "3":
                    res = num1 * num2;
                    resultado = res.ToString();
                    break;
                case "4":
                    res = num1 / num2;
                    resultado = res.ToString();
                    break;
                default:
                     resultado = "Elija una opcion valida";
                    break;

            }

            ViewBag.Resultado= resultado;

            return View();
        }

    }
}

IDGS903_Tema1/Controllers/PuntosController.cs
using IDGS903_Tema1.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace IDGS903_Tema1.Controllers
{
    public class PuntosController : Controller
    {
        // GET: Puntos
        public ActionResult Index(Puntos punt)
        {
            

            return View(punt);
        }

        public ActionResult Resultado(Puntos punt)
        {
            punt.CalcularDistancia();
            ViewBag.Distancia = punt.Distancia;

            return View(punt);
        }
    }
}

IDGS903_Tema1/Controllers/TiendaController.cs
using IDGS903_Tema1.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using IDGS903_Tema1.Models;

namespace IDGS903_Tema1.Controllers
{
    public class TiendaController : Controller
    {
        // GET: Tienda
        public ActionResult MuestraPulques()
        {
            var pulquesVenta = new PulqueServices();
            var model = pulquesVenta.ObtenerPulque();

            TempData["Nombres"] = "Juana Citlalli";

            return View(model);
        }

        public ActionResult MuestraPulques2()
        {
            var pulquesVenta = new PulqueServices();
            var model = pulquesVenta.ObtenerPulque();

            return View(model);
        }

        public ActionResult Index()
        {
            return Content("Hi, I'm Juana Citlalli Martínez Medina from ASP.NET");
            //Devuelve el texto en el body del html
        }

        public ViewResult Index2()
        {
            return View();
            //Devuelve una vista
        }

        public JsonResult Index3()
        {
            var pulque1 = new Pulques() { Nombre = "PulqueMango", Descripcion = "Maguito", Litros = 4 };
            return Json(pulque1, JsonRequestBehavior.AllowGet);
            //Devuelve JSON
        }

        public RedirectResult Index4()
        {
            return Redirect("https://google.com.mx");
            //Redirige a un link cuando se abre la vista
        }

        public RedirectToRouteResult Index5()
        {
            return RedirectToAction("MuestraPulques2");
            //Dirige a una accion del controlador que se está usando
        }

        public ActionResult Index6()
        {
            ViewBag.saludo = "Hola mundo";
            ViewBag.fecha = new DateTime(2023, 11, 2);

            ViewData["Nombre"] = "Citlalli";

            String Nombres = "";
            if(TempData.ContainsKey("Nombre"))
            {
                Nombres = TempData["Nombres"] as String;
            }
            ViewBag.nombreNuevo = Nombres;

            return View();
        }

        public ActionResult Index7()
        {
            var pulque1 = new Pulques() 
            { Nombre = "PulqueMango", Descripcion = "Maguito", Litros = 4, Caducidad= new DateTime(2023,12,4)};
            ViewBag.pulques = pulque1;
            return View();
        }


    }
}

IDGS903_Tema1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mi aplicación ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">
        <div class="container">
            @Html.ActionLink("IDGS Citlalli Martínez", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Alternar navegación" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li>@Html.ActionLink("Calculadora", "Calculos", "Nuevo2", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Pulque", "MuestraPulques2", "Tienda", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Distancia", "Index", "Puntos", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Diccionario", "RegistrarPalabras", "Diccionario", new { area = "" }, new { @class = "nav-link" })</li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Mi aplicación ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>